PRODUCT_NAME_ALLOWED_SYMBOLS = "a-zA-Z0-9_."
DEFAULT_PRODUCT_TEMPLATE = "{family}{Variant}"
PRE_CREATE_THUMBNAIL_KEY = "thumbnail_source"
DEFAULT_VARIANT_VALUE = "Main"


__all__ = (
    "PRODUCT_NAME_ALLOWED_SYMBOLS",
    "DEFAULT_PRODUCT_TEMPLATE",
    "PRE_CREATE_THUMBNAIL_KEY",
    "DEFAULT_VARIANT_VALUE",
)
