name: Deploy MkDocs

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build-mk-docs:
    uses: ynput/ops-repo-automation/.github/workflows/deploy_mkdocs.yml@feature/34-add-mk-docs-reusable-workflow
    with:
      repo: ${{ github.repository }}
    secrets:
      YNPUT_BOT_TOKEN: ${{ secrets.YNPUT_BOT_TOKEN }}
      CI_USER: ${{ secrets.CI_USER }}
      CI_EMAIL: ${{ secrets.CI_EMAIL }}
