name: 🐞 Update Bug Report

on:
  workflow_run:
    workflows: ["🚀 Release Trigger"]
    types:
      - completed
  workflow_dispatch:

jobs:
  update-bug-report:
    runs-on: ubuntu-latest
    name: Update bug report
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.target_commitish }}
      - name: Update version
        uses: ynput/gha-populate-form-version@main
        with:
          github_token: ${{ secrets.YNPUT_BOT_TOKEN }}
          registry: github
          dropdown: _version
          limit_to: 100
          form: .github/ISSUE_TEMPLATE/bug_report.yml
          commit_message: 'chore(): update bug report / version'
          dry_run: no-push

      - name: Push to protected develop branch
        uses: CasperWA/push-protected@v2.10.0
        with:
          token: ${{ secrets.YNPUT_BOT_TOKEN }}
          branch: develop
          unprotect_reviews: true