name: 🔎 Validate PR Labels
on:
  pull_request:
    types:
      - opened
      - edited
      - labeled
      - unlabeled

jobs:
  validate-type-label:
    uses: ynput/ops-repo-automation/.github/workflows/validate_pr_labels.yml@main
    with:
      repo: "${{ github.repository }}"
      pull_request_number: ${{ github.event.pull_request.number }}
      query_prefix: "type: "
    secrets:
      token: ${{ secrets.YNPUT_BOT_TOKEN }}
