"""Shared, non-blocking source of round user-avatar pixmaps.

Widgets that show a single user can simply build an :class:`AYUserImage`.
Painters that render many users - table cells, item delegates - need a
pixmap on the paint path without touching the network, which is what this
cache provides: initials are available immediately, and the real avatar
replaces them once it has been downloaded in the background.
"""

from __future__ import annotations

from functools import lru_cache
import os
import tempfile
import time

import ayon_api
from qtpy import QtCore, QtGui, QtWidgets, shiboken

from ayon_core.lib import Logger

from .task_queue import AsyncTask, get_task_queue
from .user_image import AYUserImage
from ..image_cache import ImageCache

log = Logger.get_logger(__name__)

#: Background priority - avatars are decoration, never blocking content.
_FETCH_PRIORITY = 10

#: Avatar diameter that fits a default row of the item views.
ITEM_AVATAR_SIZE = 18


def _is_generated_initials(content: bytes) -> bool:
    """Tell whether an avatar is the initials generated by the server.

    For a user without an avatar the server responds with an SVG of the
    initials, centered with the 'dominant-baseline' attribute. Qt does
    not support the attribute and draws the text off center. An uploaded
    SVG avatar is not matched, unless it would have the same issue.

    Args:
        content: Start of the avatar image.

    Returns:
        True if initials should be rendered locally instead.
    """
    head = bytes(content[:1024]).lower()
    return b"<svg" in head and b"dominant-baseline" in head


def _read_file_head(file_path: str) -> bytes:
    """Read the start of a cached avatar image.

    The image cache is shared by all AYON processes on the machine. On
    Windows the file cannot be opened at the moment another process is
    storing it, so the read is repeated for a short time.

    Args:
        file_path: Path to the cached image file.

    Returns:
        Start of the file content.
    """
    attempts = 5
    for attempt in range(attempts):
        try:
            with open(file_path, "rb") as stream:
                return stream.read(1024)
        except PermissionError:
            if attempt == attempts - 1:
                raise
            # Called in a background thread
            time.sleep(0.05)
    return b""


def _fetch_avatar_file(user_name: str) -> str:
    """Download a user avatar and return the cached file path.

    Args:
        user_name: Login name of the user.

    Returns:
        Path to the cached image file, or ``""`` when the server has no
        avatar for this user.
    """
    connection = ayon_api.get_server_api_connection()
    if connection is None:
        return ""
    response = connection.raw_get(f"users/{user_name}/avatar")
    content = getattr(response, "content", None)
    if not content:
        return ""
    if _is_generated_initials(content):
        return ""
    content_type = getattr(response, "content_type", "") or ""
    ext = ".jpg" if "jpeg" in content_type else ".png"
    with tempfile.NamedTemporaryFile(suffix=ext, delete=False) as handle:
        handle.write(content)
        return handle.name


class UserAvatarCache(QtCore.QObject):
    """Cache of round avatar pixmaps keyed by user name and size.

    :meth:`pixmap` never blocks: it returns an initials avatar right away
    and schedules the real image, emitting :attr:`avatar_updated` when the
    download lands so views can repaint.
    """

    #: Emitted with the login name once a downloaded avatar replaced the
    #: initials placeholder for that user.
    avatar_updated = QtCore.Signal(str)

    def __init__(self, parent: QtCore.QObject | None = None) -> None:
        super().__init__(parent)
        self._pixmaps: dict[tuple[str, int], QtGui.QPixmap] = {}
        self._sources: dict[str, str] = {}
        self._pending: set[str] = set()

    def clear(self) -> None:
        """Drop every cached pixmap and downloaded source path."""
        self._pixmaps.clear()
        self._sources.clear()

    def pixmap(
        self,
        user_name: str,
        full_name: str,
        size: int,
    ) -> QtGui.QPixmap | None:
        """Return the avatar for *user_name*, scheduling a download once.

        Args:
            user_name: Login name, used as the cache key and for initials.
            full_name: Display name the initials are derived from.
            size: Avatar diameter in logical pixels.

        Returns:
            A rendered pixmap, or ``None`` when there is nothing to draw.
        """
        if not user_name:
            return None
        key = (user_name, int(size))
        pixmap = self._pixmaps.get(key)
        if pixmap is None:
            pixmap = self._render(user_name, full_name, int(size))
            self._pixmaps[key] = pixmap
        self._schedule_fetch(user_name)
        return pixmap

    def _render(
        self, user_name: str, full_name: str, size: int
    ) -> QtGui.QPixmap:
        """Render one avatar through :class:`AYUserImage`.

        The widget is only a renderer here - it is never shown - so the
        avatars stay identical to the ones the rest of the UI draws.
        """
        src = self._sources.get(user_name, "")
        if src and not os.path.exists(src):
            # The image cache is shared by all AYON processes on the
            #   machine, any of them may have evicted the file meanwhile.
            #   Fall back to initials and let it be downloaded again.
            del self._sources[user_name]
            src = ""
        widget = AYUserImage(
            src=src,
            name=user_name,
            full_name=full_name or user_name,
            size=size,
            outline=False,
        )
        pixmap = widget.pxm
        widget.deleteLater()
        return pixmap

    def _schedule_fetch(self, user_name: str) -> None:
        """Queue a one-off background download of *user_name*'s avatar."""
        if user_name in self._sources or user_name in self._pending:
            return
        self._pending.add(user_name)

        def _work() -> str:
            cache = ImageCache.get_instance()
            try:
                file_path = cache.get(
                    f"user-avatar/{user_name}",
                    lambda: _fetch_avatar_file(user_name),
                )
                # Generated initials may be cached from before they
                #   were skipped on download.
                if file_path and _is_generated_initials(
                    _read_file_head(file_path)
                ):
                    return ""
                return file_path
            except Exception:  # noqa: BLE001 - avatars are optional
                log.debug(
                    "Could not fetch avatar for %r", user_name, exc_info=True
                )
                return ""

        def _done(file_path: str) -> None:
            # The cache outlives no view, but a queued download can land
            # after the owning widget was torn down.
            if shiboken.isValid(self):
                self._on_avatar_ready(user_name, file_path)

        get_task_queue().enqueue(
            AsyncTask(
                name=f"fetch_avatar:{user_name}",
                function=_work,
                callback=_done,
                priority=_FETCH_PRIORITY,
                context_id="user-avatars",
                cancellable=False,
            )
        )

    def _on_avatar_ready(self, user_name: str, file_path: str) -> None:
        """Swap the initials placeholder for the downloaded avatar."""
        self._pending.discard(user_name)
        if not file_path:
            # Remember the miss so the download is not retried per repaint.
            self._sources[user_name] = ""
            return
        self._sources[user_name] = file_path
        for key in [k for k in self._pixmaps if k[0] == user_name]:
            del self._pixmaps[key]
        self.avatar_updated.emit(user_name)


@lru_cache
def _get_max_screen_pixel_ratio() -> float:
    application = QtWidgets.QApplication.instance()
    screens = application.screens()
    if not screens:
        return 1.0
    pixel_ratio = max(
        screen.devicePixelRatio()
        for screen in screens
    )
    return max(pixel_ratio, 1.0)


def set_avatar_decoration(
    option: QtWidgets.QStyleOptionViewItem,
    avatar_cache: UserAvatarCache,
    user_name: str | None,
    full_name: str | None = None,
    size: int = ITEM_AVATAR_SIZE,
) -> None:
    """Show the avatar of a user as the decoration of a view item.

    Meant to be called from ``initStyleOption`` of an item delegate, so
    the avatar is painted the same way as an icon of the item, to the
    left of its text. The view should repaint on
    :attr:`UserAvatarCache.avatar_updated`.

    Args:
        option: Style option of the painted item.
        avatar_cache: Cache the avatar is taken from.
        user_name: Login name of the user, nothing is changed without it.
        full_name: Display name the initials are derived from.
        size: Avatar diameter in logical pixels.
    """
    if not user_name:
        return

    pix_size = int(size * _get_max_screen_pixel_ratio())
    pixmap = avatar_cache.pixmap(user_name, full_name or "", pix_size)
    if pixmap is None or pixmap.isNull():
        return
    option.icon = QtGui.QIcon(pixmap)
    option.decorationSize = QtCore.QSize(size, size)
    option.features |= QtWidgets.QStyleOptionViewItem.HasDecoration
